=head1 NAME

parrot-lolcode - a LOLCODE compiler

=head1 SYNOPSIS

  $ parrot-lolcode
  $ parrot-lolcode script.lol
  $ parrot-lolcode --target=parse script.lol
                            PAST
                            POST
                            PIR

=head1 DESCRIPTION

See L<http://en.wikipedia.org/wiki/LOLCODE>

=head1 COPYRIGHT AND LICENSE

Copyright 2008-2011, Parrot Foundation.

This program is free software; you may redistribute it and/or modify
it under the same terms as Parrot itself.

=cut

# Local Variables:
#   mode: pir
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4 ft=pir:

